#!/bin/bash

set -e
set -x
echo "Running in $(pwd)"

docker run --rm --privileged multiarch/qemu-user-static --reset --persistent yes

archs="aarch64"
for arch in ${archs}; do
	docker run --rm --name hassio-builder --privileged -v $(pwd):/data -v /var/run/docker.sock:/var/run/docker.sock:ro homeassistant/amd64-builder -t /data --${arch} --test -i almond-hassio-addon-{arch} --no-latest
done
