#!/bin/bash

set -e
set -x

NOW=$(date +%m%d%Y)

sed -i s@"\"version\": \".*\""@"\"version\": \"edge-${NOW}\""@ $(pwd)/config.json
git config user.email "you@example.com"
git config user.name "Your Name"
git commit -m "Edge Build ${NOW}"
git push -u origin master
