---
channel: unofficial
addons:
  almond-nightly:
    repository: ad31c0/almond-hassio-addon/nightly
    target: almond-nightly
    image: ad31c0/almond-hassio-addon/{arch}-nightly
  almond-alpha:
    repository: ad31c0/almond-hassio-addon/alpha
    target: almond-alpha
    image: ad31c0/almond-hassio-addon/{arch}-alpha
  almond-beta:
    repository: ad31c0/almond-hassio-addon/beta
    target: almond-beta
    image: ad31c0/almond-hassio-addon/{arch}-beta
