#!/bin/bash

set -e
set -x
echo "Running in $(pwd)"
env

archs="armv7"
for arch in ${archs}; do
	docker run --rm --name hassio-builder --privileged -v $(pwd):/data -v /var/run/docker.sock:/var/run/docker.sock:ro homeassistant/amd64-builder -t /data --${arch} --test -i almond-hassio-addon --release-tag --release ${arch}-nightly
	docker tag ad31c0/almond-hassio-addon:edge ad31c0/almond-hassio-addon:latest
done
